import { NextRequest } from "next/server";
import { assertSameOrigin,jsonNoStore } from "@/lib/auth/security";
import { requireStaff } from "@/lib/auth/session";
import { supabaseFetch } from "@/lib/supabase/server";
import { auditTimeEntry } from "@/lib/manual-sheets/audit";

type Context={params:Promise<{publicId:string}>};
const occurrences=new Set(["worked","absence","day_off","medical_leave","vacation","holiday","other"]);
export async function GET(_request:NextRequest,context:Context){const session=await requireStaff();if(!session)return jsonNoStore({error:"Acesso não autorizado."},403);const {publicId}=await context.params;const result=await supabaseFetch(`/rest/v1/manual_time_entries?select=public_id,work_date,occurrence,clock_in,break_start,break_end,clock_out,notes,employees(public_id,full_name,registration_number)&manual_sheet_batches!inner(public_id)&manual_sheet_batches.public_id=eq.${publicId}&order=work_date`,{token:session.token});if(!result.response.ok)return jsonNoStore({error:"Não foi possível carregar os lançamentos."},500);return jsonNoStore({entries:result.data||[]});}
export async function POST(request:NextRequest,context:Context){
  try{assertSameOrigin(request);}catch{return jsonNoStore({error:"Origem inválida."},403);}const session=await requireStaff();if(!session)return jsonNoStore({error:"Acesso não autorizado."},403);const {publicId}=await context.params;const body=await request.json() as Record<string,unknown>;const employeePublicId=String(body.employeeId||"");const workDate=String(body.workDate||"");const occurrence=String(body.occurrence||"worked");const value=(key:string)=>{const text=String(body[key]||"");return /^([01]\d|2[0-3]):[0-5]\d$/.test(text)?text:null;};const notes=String(body.notes||"").trim().slice(0,1000)||null;
  if(!/^[a-f0-9]{24}$/.test(publicId)||!/^[a-f0-9]{24}$/.test(employeePublicId)||!/^\d{4}-\d{2}-\d{2}$/.test(workDate)||!occurrences.has(occurrence))return jsonNoStore({error:"Dados inválidos."},400);
  const [batchResult,employeeResult]=await Promise.all([supabaseFetch<Array<{id:string;company_id:string;work_site_id:string;competence:string;status:string}>>(`/rest/v1/manual_sheet_batches?select=id,company_id,work_site_id,competence,status&public_id=eq.${publicId}&limit=1`,{token:session.token}),supabaseFetch<Array<{id:string;company_id:string;shift_pattern:string|null}>>(`/rest/v1/employees?select=id,company_id,shift_pattern&public_id=eq.${employeePublicId}&limit=1`,{token:session.token})]);const batch=batchResult.data?.[0];const employee=employeeResult.data?.[0];if(!batch||!employee||batch.company_id!==employee.company_id||batch.status!=="draft"||!workDate.startsWith(batch.competence.slice(0,7)))return jsonNoStore({error:"Folha, funcionário ou data inválidos."},409);
  const clockIn=value("clockIn"),clockOut=value("clockOut");if(occurrence==="worked"&&(!clockIn||!clockOut))return jsonNoStore({error:"Entrada e saída são obrigatórias em dia trabalhado."},400);
  const insert=await supabaseFetch<Array<{id:string}>>("/rest/v1/manual_time_entries?select=id",{method:"POST",serviceRole:true,headers:{Prefer:"return=representation"},body:JSON.stringify({batch_id:batch.id,employee_id:employee.id,company_id:batch.company_id,work_site_id:batch.work_site_id,work_date:workDate,occurrence,clock_in:clockIn,break_start:value("breakStart"),break_end:value("breakEnd"),clock_out:clockOut,notes,created_by:session.user.id,updated_by:session.user.id})});if(!insert.response.ok)return jsonNoStore({error:"Já existe lançamento para este funcionário nessa data."},409);
  const inconsistencies=auditTimeEntry({occurrence,clockIn,breakStart:value("breakStart"),breakEnd:value("breakEnd"),clockOut,shiftPattern:employee.shift_pattern});
  await supabaseFetch("/rest/v1/audit_logs",{method:"POST",serviceRole:true,headers:{Prefer:"return=minimal"},body:JSON.stringify({actor_user_id:session.user.id,action:"manual_entry.created",entity_table:"manual_time_entries",entity_id:insert.data?.[0]?.id,metadata:{work_date:workDate,occurrence,inconsistencies}})});return jsonNoStore({ok:true,inconsistencies},201);
}
