"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { Bot,Building2,CalendarRange,Download,FileCheck2,FileUp,PenLine,Plus,RefreshCw,Search,ShieldCheck,User,UserPlus } from "lucide-react";
import {formatCpf,isValidCpf,normalizeCpf} from "@/lib/cpf";
import { MonthYearPicker } from "./MonthYearPicker";
import styles from "./manual-sheets.module.css";

type Company={public_id:string;display_name:string};
type Site={public_id:string;name:string;companies?:{public_id:string;display_name:string}|null};
type Employee={public_id:string;full_name:string;registration_number:string|null;companies?:{public_id:string;display_name:string}|null};
type Batch={public_id:string;competence:string;status:string;original_filename:string|null;created_at:string;companies?:Company|null;work_sites?:Site|null};
type Entry={public_id:string;work_date:string;occurrence:string;clock_in:string|null;break_start:string|null;break_end:string|null;clock_out:string|null;employees?:Employee|null};
type Extracted={include?:boolean;employeePublicId:string|null;employeeNameRead:string;workDate:string;occurrence:string;clockIn:string|null;breakStart:string|null;breakEnd:string|null;clockOut:string|null;confidence:number;warning:string|null};
type Extraction={public_id:string;status:string;structured_result?:{rows?:Extracted[];warnings?:string[]};error_message?:string};
const monthNow=()=>new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit"}).slice(0,7);
const emptyEntry={employeeId:"",workDate:"",occurrence:"worked",clockIn:"",breakStart:"",breakEnd:"",clockOut:"",notes:""};

export function ManualSheetsDashboard(){
  const [role,setRole]=useState("");const [companies,setCompanies]=useState<Company[]>([]);const [sites,setSites]=useState<Site[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [batches,setBatches]=useState<Batch[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [selected,setSelected]=useState("");
  const [upload,setUpload]=useState({companyId:"",siteId:"",month:monthNow(),notes:""});const [employee,setEmployee]=useState({companyId:"",siteId:"",fullName:"",registration:"",cpf:"",jobTitle:""});const [entry,setEntry]=useState(emptyEntry);const [file,setFile]=useState<File|null>(null);const [extraction,setExtraction]=useState<Extraction|null>(null);const [rows,setRows]=useState<Extracted[]>([]);
  const [employeeSearch,setEmployeeSearch]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const [d,b]=await Promise.all([fetch("/api/admin/dashboard",{cache:"no-store"}),fetch("/api/admin/manual-sheets",{cache:"no-store"})]);const dashboard=await d.json(),batchData=await b.json();if(!d.ok||!b.ok)throw new Error(dashboard.error||batchData.error);setRole(dashboard.role);setCompanies(dashboard.companies||[]);setSites(dashboard.sites||[]);setEmployees(dashboard.employees||[]);setBatches(batchData.batches||[]);const firstBatch=batchData.batches?.[0];const company=firstBatch?.companies?.public_id||dashboard.companies?.[0]?.public_id||"";const site=firstBatch?.work_sites?.public_id||dashboard.sites?.find((item:Site)=>item.companies?.public_id===company)?.public_id||"";const month=firstBatch?.competence?.slice(0,7)||monthNow();setUpload(current=>current.companyId?current:{...current,companyId:company,siteId:site,month});setEmployee(current=>({...current,companyId:current.companyId||company,siteId:current.siteId||site}));const firstEmployee=dashboard.employees?.find((item:Employee)=>item.companies?.public_id===company);setEntry(current=>({...current,employeeId:current.employeeId||firstEmployee?.public_id||"",workDate:current.workDate||`${month}-01`}));setSelected(current=>current||firstBatch?.public_id||"");},[]);
  const loadEntries=useCallback(async(id:string)=>{if(!id){setEntries([]);setExtraction(null);setRows([]);return;}const [entryResponse,extractResponse]=await Promise.all([fetch(`/api/admin/manual-sheets/${id}/entries`,{cache:"no-store"}),fetch(`/api/admin/manual-sheets/${id}/extraction`,{cache:"no-store"})]);const body=await entryResponse.json(),extractBody=await extractResponse.json();if(!entryResponse.ok)throw new Error(body.error);setEntries(body.entries||[]);const latest=extractResponse.ok?extractBody.extraction||null:null;setExtraction(latest);setRows((latest?.structured_result?.rows||[]).map((row:Extracted)=>({...row,include:true})));},[]);
  useEffect(()=>{void load().catch(reason=>setError(reason.message));},[load]);useEffect(()=>{void loadEntries(selected).catch(reason=>setError(reason.message));},[selected,loadEntries]);
  useEffect(()=>{const channel=new BroadcastChannel("ds-servicos-cadastros");channel.onmessage=event=>{if(event.data?.type!=="registration-created")return;void load().then(()=>setMessage("Cadastro concluído em outra aba. As listas foram atualizadas.")).catch(reason=>setError(reason.message));};return()=>channel.close();},[load]);
  const sitesFor=(companyId:string)=>sites.filter(site=>site.companies?.public_id===companyId);const activeBatch=batches.find(batch=>batch.public_id===selected);const availableEmployees=employees.filter(item=>item.companies?.public_id===activeBatch?.companies?.public_id);
  const uploadSites=sitesFor(upload.companyId);const employeeSites=sitesFor(employee.companyId);
  async function act(work:()=>Promise<void>){setBusy(true);setError("");setMessage("");try{await work();}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível concluir.");}finally{setBusy(false);}}
  async function createEmployee(event:FormEvent){event.preventDefault();await act(async()=>{const response=await fetch("/api/admin/employees",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(employee)});const body=await response.json();if(!response.ok)throw new Error(body.error);setEmployee(current=>({...current,fullName:"",registration:"",cpf:"",jobTitle:""}));setMessage("Funcionário cadastrado e vinculado à empresa.");await load();});}
  async function sendSheet(event:FormEvent){event.preventDefault();if(!file)return;await act(async()=>{const data=new FormData();Object.entries(upload).forEach(([key,value])=>data.set(key,value));data.set("document",file);const response=await fetch("/api/admin/manual-sheets",{method:"POST",body:data});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage("Folha original armazenada com segurança.");setFile(null);await load();setSelected(body.publicId);});}
  async function startWithoutSheet(){await act(async()=>{const response=await fetch("/api/admin/manual-sheets",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(upload)});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage("Competência iniciada. Os lançamentos estão liberados; anexe a folha quando ela chegar.");await load();setSelected(body.publicId);const first=employees.find(item=>item.companies?.public_id===upload.companyId);setEntry(current=>({...current,employeeId:first?.public_id||"",workDate:suggestedDate(upload.month)}));});}
  async function sendEntry(event:FormEvent){event.preventDefault();if(!selected)return;await act(async()=>{const response=await fetch(`/api/admin/manual-sheets/${selected}/entries`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(entry)});const body=await response.json();if(!response.ok)throw new Error(body.error);const currentIndex=availableEmployees.findIndex(item=>item.public_id===entry.employeeId);const nextEmployee=availableEmployees[currentIndex+1]||availableEmployees[0];setEntry(current=>({...emptyEntry,employeeId:nextEmployee?.public_id||"",workDate:current.workDate}));setMessage(body.inconsistencies?.length?`Lançamento salvo com ${body.inconsistencies.length} inconsistência(s): ${body.inconsistencies.join(" ")}`:"Lançamento salvo. O próximo funcionário foi selecionado.");await loadEntries(selected);});}
  async function readSheet(){await act(async()=>{const response=await fetch(`/api/admin/manual-sheets/${selected}/extraction`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error);setExtraction({public_id:body.publicId,status:body.status,structured_result:body.structured_result});setRows((body.structured_result?.rows||[]).map((row:Extracted)=>({...row,include:true})));setMessage("Leitura concluída. Confira cada linha antes de confirmar.");});}
  async function confirmRows(){if(!extraction)return;await act(async()=>{const response=await fetch(`/api/admin/manual-sheets/${selected}/extraction`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({extractionId:extraction.public_id,rows})});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage(`${body.compared||0} lançamento(s) diário(s) comparado(s) e ${body.inserted||0} registro(s) ausente(s) importado(s) da folha.`);await loadEntries(selected);});}
  function selectBatch(id:string){setSelected(id);const batch=batches.find(item=>item.public_id===id);const first=employees.find(item=>item.companies?.public_id===batch?.companies?.public_id);setEntry(current=>({...current,employeeId:first?.public_id||""}));}
  function suggestedDate(month:string){const now=new Date();now.setDate(now.getDate()-1);const yesterday=now.toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"});return yesterday.startsWith(month)?yesterday:`${month}-01`;}
  function changeContext(next:Partial<typeof upload>){
    const context={...upload,...next};if(next.companyId!==undefined&&!next.siteId)context.siteId=sitesFor(context.companyId)[0]?.public_id||"";
    setUpload(context);const match=batches.find(item=>item.companies?.public_id===context.companyId&&item.work_sites?.public_id===context.siteId&&item.competence.slice(0,7)===context.month);
    selectBatch(match?.public_id||"");const first=employees.find(item=>item.companies?.public_id===context.companyId);setEntry(current=>({...current,employeeId:first?.public_id||"",workDate:suggestedDate(context.month)}));
  }
  function openQuickRegistration(entity:"company"|"site"|"employee"){const params=new URLSearchParams({new:entity,popup:"1"});if(entity!=="company"&&upload.companyId)params.set("companyId",upload.companyId);window.open(`/administrativo/ponto/cadastros?${params.toString()}`,"_blank","noopener,noreferrer");}
  const updateRow=(index:number,key:keyof Extracted,value:unknown)=>setRows(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row));
  const activeEmployee=availableEmployees.find(item=>item.public_id===entry.employeeId);
  const visibleEntries=entry.employeeId?entries.filter(item=>item.employees?.public_id===entry.employeeId):entries;
  const shownEmployees=availableEmployees.filter(item=>`${item.full_name} ${item.registration_number||""}`.toLocaleLowerCase("pt-BR").includes(employeeSearch.toLocaleLowerCase("pt-BR")));
  return <div className={styles.wrapper}>
    <div className={styles.notice}><ShieldCheck/><div><strong>Controle por folha manuscrita</strong><p>A folha assinada é preservada. A leitura automática apenas propõe dados e exige confirmação do operador.</p></div></div>
    {(error||message)&&<p className={error?styles.error:styles.success}>{error||message}</p>}
    <section className={styles.contextPanel}><div className={styles.contextTitle}><div><span>1</span><div><small>Contexto do lançamento</small><h2>Selecione empresa, posto e competência</h2></div></div>{activeBatch?.original_filename?<p className={styles.ready}><FileCheck2/>Folha anexada</p>:<p className={styles.pending}><FileUp/>{activeBatch?"Lançamentos liberados · folha pendente":"Competência ainda não iniciada"}</p>}</div><div className={styles.contextGrid}>
      <label><span className={styles.fieldLabel}><span><Building2/>Empresa</span>{role==="admin"&&<button type="button" className={styles.addButton} title="Cadastrar nova empresa em outra aba" aria-label="Cadastrar nova empresa em outra aba" onClick={()=>openQuickRegistration("company")}><Plus/></button>}</span><select value={upload.companyId} onChange={e=>changeContext({companyId:e.target.value,siteId:""})}>{companies.map(x=><option key={x.public_id} value={x.public_id}>{x.display_name}</option>)}</select></label>
      <label><span className={styles.fieldLabel}><span><Building2/>Posto</span>{["admin","supervisor"].includes(role)&&<button type="button" className={styles.addButton} title="Cadastrar novo posto em outra aba" aria-label="Cadastrar novo posto em outra aba" onClick={()=>openQuickRegistration("site")}><Plus/></button>}</span><select value={upload.siteId} onChange={e=>changeContext({siteId:e.target.value})}><option value="">Selecione</option>{uploadSites.map(x=><option key={x.public_id} value={x.public_id}>{x.name}</option>)}</select></label>
      <label><span><CalendarRange/>Mês e ano</span><MonthYearPicker value={upload.month} onChange={month=>changeContext({month})}/></label>
    </div><p className={styles.contextHelp}>{activeBatch?<>Você está trabalhando em <strong>{activeBatch.companies?.display_name}</strong>, posto <strong>{activeBatch.work_sites?.name}</strong>, competência <strong>{activeBatch.competence.slice(0,7)}</strong>. {activeBatch.original_filename?"A folha assinada já está vinculada.":"Você pode lançar agora e anexar a folha posteriormente."}</>:<>A competência ainda não existe. Você pode iniciá-la agora, sem esperar a folha assinada.</>}</p>{!activeBatch&&<button type="button" className={styles.startButton} disabled={busy||!upload.companyId||!upload.siteId||!upload.month} onClick={startWithoutSheet}><PenLine/>Iniciar lançamentos sem folha</button>}</section>
    {["admin","supervisor"].includes(role)&&<section><h2><UserPlus/>Cadastro rápido de funcionário</h2><form className={styles.grid} onSubmit={createEmployee}>
      <label>Empresa<select required value={employee.companyId} onChange={e=>setEmployee({...employee,companyId:e.target.value,siteId:""})}>{companies.map(x=><option key={x.public_id} value={x.public_id}>{x.display_name}</option>)}</select></label>
      <label>Posto<select required value={employee.siteId} onChange={e=>setEmployee({...employee,siteId:e.target.value})}><option value="">Selecione</option>{employeeSites.map(x=><option key={x.public_id} value={x.public_id}>{x.name}</option>)}</select></label>
      <label>Nome completo<input required minLength={3} value={employee.fullName} onChange={e=>setEmployee({...employee,fullName:e.target.value})}/></label>
      <label>Matrícula (opcional)<input value={employee.registration} onChange={e=>setEmployee({...employee,registration:e.target.value})}/></label>
      <label>CPF<input required inputMode="numeric" autoComplete="off" maxLength={14} placeholder="000.000.000-00" value={employee.cpf} onChange={e=>{const value=formatCpf(e.target.value);e.currentTarget.setCustomValidity(normalizeCpf(value).length===11&&!isValidCpf(value)?"Informe um CPF válido.":"");setEmployee({...employee,cpf:value});}} onBlur={e=>e.currentTarget.setCustomValidity(isValidCpf(e.currentTarget.value)?"":"Informe um CPF válido.")}/></label>
      <label>Cargo<input value={employee.jobTitle} onChange={e=>setEmployee({...employee,jobTitle:e.target.value})}/></label>
      <button className={styles.primary} disabled={busy}><UserPlus/>Cadastrar</button>
    </form></section>}
    {!activeBatch?.original_filename&&<section><h2><FileUp/>{activeBatch?"Anexar":"Ou enviar"} folha assinada</h2><p>{activeBatch?"Os lançamentos já estão liberados. Anexe o documento quando estiver disponível.":"Se a folha já estiver disponível, envie-a e a competência será criada automaticamente."}</p><form className={styles.grid} onSubmit={sendSheet}>
      <label>Folha assinada<input type="file" accept=".pdf,image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label>
      <label className={styles.wide}>Observações<input value={upload.notes} onChange={e=>setUpload({...upload,notes:e.target.value})}/></label>
      <button className={styles.primary} disabled={busy||!file}><FileUp/>Enviar folha</button>
    </form></section>}
    <section className={!activeBatch?styles.disabledSection:undefined}><h2><PenLine/>2. Lançamento diário</h2>
      {!activeBatch&&<p className={styles.emptyState}>Inicie a competência acima para liberar os lançamentos. A folha pode ser anexada depois.</p>}
      {selected&&<div className={styles.actions}>{activeBatch?.original_filename&&<button type="button" className={styles.secondary} disabled={busy} onClick={readSheet}><Bot/>Ler folha automaticamente</button>}{activeBatch?.original_filename?<a className={styles.download} href={`/api/admin/manual-sheets/${selected}/report`}><Download/>PDF com folha original</a>:<span className={styles.documentPending}>Folha assinada pendente</span>}</div>}
      {extraction?.status==="review"&&<div className={styles.review}><h3>Revisão obrigatória da leitura</h3><p>Confirme nomes, datas e horários. Linhas desmarcadas não serão lançadas.</p><div className={styles.table}><table><thead><tr><th>Usar</th><th>Funcionário</th><th>Data</th><th>Ocorrência</th><th>Entrada</th><th>Almoço</th><th>Retorno</th><th>Saída</th><th>Confiança</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${index}-${row.workDate}`}>
        <td><input type="checkbox" checked={row.include!==false} onChange={e=>updateRow(index,"include",e.target.checked)}/></td>
        <td><select value={row.employeePublicId||""} onChange={e=>updateRow(index,"employeePublicId",e.target.value||null)}><option value="">Revisar: {row.employeeNameRead}</option>{availableEmployees.map(item=><option key={item.public_id} value={item.public_id}>{item.full_name}{item.registration_number?` · ${item.registration_number}`:""}</option>)}</select></td>
        <td><input type="date" value={row.workDate} onChange={e=>updateRow(index,"workDate",e.target.value)}/></td>
        <td><select value={row.occurrence} onChange={e=>updateRow(index,"occurrence",e.target.value)}><option value="worked">Trabalhado</option><option value="absence">Falta</option><option value="day_off">Folga</option><option value="medical_leave">Atestado</option><option value="vacation">Férias</option><option value="holiday">Feriado</option><option value="other">Outra</option></select></td>
        {(["clockIn","breakStart","breakEnd","clockOut"] as const).map(key=><td key={key}><input type="time" value={row[key]||""} onChange={e=>updateRow(index,key,e.target.value||null)}/></td>)}<td title={row.warning||""}>{Math.round(row.confidence*100)}%{row.warning?" ⚠":""}</td>
      </tr>)}</tbody></table></div><button className={styles.primary} disabled={busy||!rows.some(row=>row.include!==false)} onClick={confirmRows}>Confirmar lançamentos revisados</button></div>}
      {selected&&<div className={styles.launchLayout}><aside className={styles.employeeSidebar} aria-label="Funcionários da empresa"><div className={styles.sidebarTitle}><h3>Funcionários</h3>{["admin","supervisor"].includes(role)&&<button type="button" className={styles.addButton} title="Cadastrar novo funcionário em outra aba" aria-label="Cadastrar novo funcionário em outra aba" onClick={()=>openQuickRegistration("employee")}><Plus/></button>}</div><label className={styles.employeeSearch}><Search/><input type="search" placeholder="Buscar nome ou matrícula" value={employeeSearch} onChange={e=>setEmployeeSearch(e.target.value)}/></label>{shownEmployees.map(item=><button type="button" key={item.public_id} className={item.public_id===entry.employeeId?styles.employeeActive:styles.employeeButton} onClick={()=>setEntry(current=>({...current,employeeId:item.public_id}))}><User/><span><strong>{item.full_name}</strong><small>{item.registration_number?`Matrícula ${item.registration_number}`:"Sem matrícula"}</small></span></button>)}{!shownEmployees.length&&<p>Nenhum funcionário encontrado.</p>}</aside><div className={styles.launchContent}><div className={styles.employeeHeading}><User/><div><small>Lançamento atual</small><strong>{activeEmployee?.full_name||"Selecione um funcionário"}</strong></div></div><form className={styles.grid} onSubmit={sendEntry}><label>Data<input type="date" value={entry.workDate} onChange={e=>setEntry({...entry,workDate:e.target.value})} required/></label><label>Ocorrência<select value={entry.occurrence} onChange={e=>setEntry({...entry,occurrence:e.target.value})}><option value="worked">Trabalhado</option><option value="absence">Falta</option><option value="day_off">Folga</option><option value="medical_leave">Atestado</option><option value="vacation">Férias</option><option value="holiday">Feriado</option><option value="other">Outra</option></select></label>{(["clockIn","breakStart","breakEnd","clockOut"] as const).map((key,index)=><label key={key}>{["Entrada","Saída almoço","Retorno almoço","Saída"][index]}<input type="time" value={entry[key]} onChange={e=>setEntry({...entry,[key]:e.target.value})}/></label>)}<label className={styles.wide}>Observação<input value={entry.notes} onChange={e=>setEntry({...entry,notes:e.target.value})}/></label><button className={styles.primary} disabled={busy||!entry.employeeId}><PenLine/>Salvar e avançar</button></form></div></div>}
      <div className={styles.table}><table><thead><tr><th>Data</th><th>Funcionário</th><th>Ocorrência</th><th>Entrada</th><th>Almoço</th><th>Retorno</th><th>Saída</th></tr></thead><tbody>{visibleEntries.map(x=><tr key={x.public_id}><td>{x.work_date}</td><td>{x.employees?.full_name}</td><td>{x.occurrence}</td><td>{x.clock_in||"—"}</td><td>{x.break_start||"—"}</td><td>{x.break_end||"—"}</td><td>{x.clock_out||"—"}</td></tr>)}</tbody></table>{!visibleEntries.length&&<p>Nenhum horário lançado para o funcionário selecionado.</p>}</div>
    </section>{busy&&<p><RefreshCw className={styles.spin}/> Processando...</p>}
  </div>;
}
