"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Building2,CheckCircle2,MapPin,RefreshCw,UserPlus} from "lucide-react";
import {formatCnpj,normalizeCnpj} from "@/lib/cnpj";
import styles from "./registrations.module.css";
type Company={public_id:string;display_name:string;legal_name:string;tax_id:string|null;is_active:boolean};
type Site={public_id:string;name:string;address:string|null;is_active:boolean;companies?:{public_id:string;display_name:string}|null};
type Employee={public_id:string;full_name:string;registration_number:string;job_title:string|null;status:string;companies?:{public_id:string;display_name:string}|null;work_sites?:{public_id:string;name:string}|null};
export function RegistrationsDashboard(){
  const [role,setRole]=useState("");const [companies,setCompanies]=useState<Company[]>([]);const [sites,setSites]=useState<Site[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  const [cnpjLookup,setCnpjLookup]=useState({loading:false,message:"",error:""});
  const [company,setCompany]=useState({legalName:"",displayName:"",taxId:""});const [site,setSite]=useState({companyId:"",name:"",address:"",latitude:"",longitude:"",radius:"150"});const [employee,setEmployee]=useState({companyId:"",siteId:"",fullName:"",registration:"",cpf:"",jobTitle:""});
  const load=useCallback(async()=>{const response=await fetch("/api/admin/dashboard",{cache:"no-store"});const body=await response.json();if(response.status===401){window.location.assign("/administrativo/login?redirect=/administrativo/ponto/cadastros");return;}if(!response.ok)throw new Error(body.error);setRole(body.role);setCompanies(body.companies||[]);setSites(body.sites||[]);setEmployees(body.employees||[]);const first=body.companies?.[0]?.public_id||"";const firstSite=body.sites?.find((item:Site)=>item.companies?.public_id===first)?.public_id||"";setSite(current=>({...current,companyId:current.companyId||first}));setEmployee(current=>({...current,companyId:current.companyId||first,siteId:current.siteId||firstSite}));},[]);
  useEffect(()=>{void load().catch(reason=>setError(reason.message));},[load]);
  useEffect(()=>{
    const cnpj=normalizeCnpj(company.taxId);
    if(cnpj.length!==14){setCnpjLookup({loading:false,message:"",error:""});return;}
    const controller=new AbortController();
    const timer=window.setTimeout(async()=>{
      setCnpjLookup({loading:true,message:"",error:""});
      try{
        const response=await fetch(`/api/admin/cnpj/${cnpj}`,{cache:"no-store",signal:controller.signal});
        const body=await response.json();
        if(!response.ok)throw new Error(body.error||"Não foi possível consultar o CNPJ.");
        setCompany(current=>normalizeCnpj(current.taxId)===cnpj?{...current,legalName:body.legalName,displayName:body.tradeName||body.legalName}:current);
        setCnpjLookup({loading:false,message:`Dados encontrados${body.status?` · Situação ${body.status}`:""}. Você ainda pode editar os campos.`,error:""});
      }catch(reason){
        if(controller.signal.aborted)return;
        setCnpjLookup({loading:false,message:"",error:reason instanceof Error?reason.message:"Não foi possível consultar o CNPJ."});
      }
    },500);
    return()=>{window.clearTimeout(timer);controller.abort();};
  },[company.taxId]);
  async function submit(path:string,payload:unknown,success:string,reset:()=>void){setBusy(true);setError("");setMessage("");try{const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok)throw new Error(body.error);reset();setMessage(success);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível cadastrar.");}finally{setBusy(false);}}
  const availableSites=sites.filter(item=>item.companies?.public_id===employee.companyId);
  if(error&&!role)return <div className={styles.readOnly}><h2>Sessão administrativa não reconhecida</h2><p>{error}</p><a className={styles.loginLink} href="/administrativo/login?redirect=/administrativo/ponto/cadastros">Entrar novamente</a></div>;
  const roleName=role==="admin"?"Administrador":role==="supervisor"?"Supervisor":role==="operator"?"Operador":"Verificando sessão...";
  if(role==="operator")return <div className={styles.readOnly}><p className={styles.role}>Perfil ativo: <strong>{roleName}</strong></p><h2>Cadastros</h2><p>Seu perfil de operador pode consultar e lançar horários, mas somente administradores e supervisores podem criar cadastros.</p></div>;
  return <div className={styles.wrapper}><div className={styles.accessInfo}><div><small>Perfil ativo</small><strong>{roleName}</strong></div>{role!=="admin"&&<p>Somente o perfil Administrador pode cadastrar empresas. Supervisores cadastram postos e funcionários da empresa vinculada.</p>}</div>{(message||error)&&<p className={error?styles.error:styles.success}>{error||message}</p>}
    {role==="admin"&&<section><h2><Building2/>Nova empresa</h2><form className={styles.form} onSubmit={(event:FormEvent)=>{event.preventDefault();void submit("/api/admin/companies",company,"Empresa cadastrada.",()=>setCompany({legalName:"",displayName:"",taxId:""}));}}><label>CNPJ<input inputMode="numeric" autoComplete="off" maxLength={18} placeholder="00.000.000/0000-00" value={company.taxId} onChange={e=>setCompany({...company,taxId:formatCnpj(e.target.value)})}/></label><label>Razão social<input required value={company.legalName} onChange={e=>setCompany({...company,legalName:e.target.value})}/></label><label>Nome de exibição<input required value={company.displayName} onChange={e=>setCompany({...company,displayName:e.target.value})}/></label>{(cnpjLookup.loading||cnpjLookup.message||cnpjLookup.error)&&<p className={`${styles.lookupStatus} ${cnpjLookup.loading?styles.lookupLoading:""} ${cnpjLookup.error?styles.lookupError:""}`}>{cnpjLookup.loading?<><RefreshCw/>Consultando CNPJ...</>:cnpjLookup.error?cnpjLookup.error:<><CheckCircle2/>{cnpjLookup.message}</>}</p>}<button disabled={busy||cnpjLookup.loading}>Cadastrar empresa</button></form><div className={styles.cards}>{companies.map(item=><article key={item.public_id}><strong>{item.display_name}</strong><small>{item.legal_name}</small></article>)}</div></section>}
    <section><h2><MapPin/>Novo posto</h2><form className={styles.form} onSubmit={(event:FormEvent)=>{event.preventDefault();void submit("/api/admin/work-sites",site,"Posto cadastrado.",()=>setSite(current=>({...current,name:"",address:"",latitude:"",longitude:"",radius:"150"})));}}><label>Empresa<select value={site.companyId} onChange={e=>setSite({...site,companyId:e.target.value})}>{companies.map(item=><option key={item.public_id} value={item.public_id}>{item.display_name}</option>)}</select></label><label>Nome do posto<input required value={site.name} onChange={e=>setSite({...site,name:e.target.value})}/></label><label className={styles.wide}>Endereço<input value={site.address} onChange={e=>setSite({...site,address:e.target.value})}/></label><button disabled={busy}>Cadastrar posto</button></form><div className={styles.cards}>{sites.map(item=><article key={item.public_id}><strong>{item.name}</strong><small>{item.companies?.display_name} · {item.address||"Sem endereço"}</small></article>)}</div></section>
    <section><h2><UserPlus/>Novo funcionário</h2><form className={styles.form} onSubmit={(event:FormEvent)=>{event.preventDefault();void submit("/api/admin/employees",employee,"Funcionário cadastrado.",()=>setEmployee(current=>({...current,fullName:"",registration:"",cpf:"",jobTitle:""})));}}><label>Empresa<select value={employee.companyId} onChange={e=>{const companyId=e.target.value;setEmployee({...employee,companyId,siteId:sites.find(item=>item.companies?.public_id===companyId)?.public_id||""});}}>{companies.map(item=><option key={item.public_id} value={item.public_id}>{item.display_name}</option>)}</select></label><label>Posto<select required value={employee.siteId} onChange={e=>setEmployee({...employee,siteId:e.target.value})}><option value="">Selecione</option>{availableSites.map(item=><option key={item.public_id} value={item.public_id}>{item.name}</option>)}</select></label><label>Nome completo<input required value={employee.fullName} onChange={e=>setEmployee({...employee,fullName:e.target.value})}/></label><label>Matrícula<input required value={employee.registration} onChange={e=>setEmployee({...employee,registration:e.target.value})}/></label><label>CPF<input required inputMode="numeric" value={employee.cpf} onChange={e=>setEmployee({...employee,cpf:e.target.value})}/></label><label>Cargo<input value={employee.jobTitle} onChange={e=>setEmployee({...employee,jobTitle:e.target.value})}/></label><button disabled={busy}>Cadastrar funcionário</button></form><div className={styles.table}><table><thead><tr><th>Funcionário</th><th>Matrícula</th><th>Empresa</th><th>Posto</th><th>Cargo</th></tr></thead><tbody>{employees.map(item=><tr key={item.public_id}><td>{item.full_name}</td><td>{item.registration_number}</td><td>{item.companies?.display_name}</td><td>{item.work_sites?.name||"—"}</td><td>{item.job_title||"—"}</td></tr>)}</tbody></table></div></section>
    {busy&&<p className={styles.loading}><RefreshCw/>Processando...</p>}
  </div>;
}
