import { NextRequest } from "next/server";
import { requireStaff } from "@/lib/auth/session";
import { jsonNoStore } from "@/lib/auth/security";
import { supabaseFetch } from "@/lib/supabase/server";

type Row={public_id:string;work_date:string;occurrence:string;clock_in:string|null;break_start:string|null;break_end:string|null;clock_out:string|null;employees:{public_id:string;full_name:string;registration_number:string|null;companies:{public_id:string;display_name:string}|null}|null;work_sites:{public_id:string;name:string}|null;manual_sheet_batches:{status:string}|null};
const validMonth=/^\d{4}-(0[1-9]|1[0-2])$/;
function nextMonth(month:string){const [year,value]=month.split("-").map(Number);return value===12?`${year+1}-01`:`${year}-${String(value+1).padStart(2,"0")}`;}
function minutes(start:string|null,end:string|null){if(!start||!end)return 0;const [sh,sm]=start.split(":").map(Number),[eh,em]=end.split(":").map(Number);return Math.max(0,eh*60+em-sh*60-sm);}
function iso(date:string,time:string|null){return time?`${date}T${time.slice(0,5)}:00-03:00`:null;}
export async function GET(request:NextRequest){const session=await requireStaff();if(!session)return jsonNoStore({error:"Acesso não autorizado."},403);const month=request.nextUrl.searchParams.get("month")||"";if(!validMonth.test(month))return jsonNoStore({error:"Competência inválida."},400);const result=await supabaseFetch<Row[]>(`/rest/v1/manual_time_entries?select=public_id,work_date,occurrence,clock_in,break_start,break_end,clock_out,employees(public_id,full_name,registration_number,companies(public_id,display_name)),work_sites(public_id,name),manual_sheet_batches!inner(status)&work_date=gte.${month}-01&work_date=lt.${nextMonth(month)}-01&order=work_date&limit=5000`,{token:session.token});if(!result.response.ok)return jsonNoStore({error:"Não foi possível gerar o fechamento das folhas."},500);const days=(result.data||[]).map(row=>{const worked=row.occurrence==="worked";const complete=!worked||Boolean(row.clock_in&&row.clock_out&&((row.break_start&&row.break_end)||(!row.break_start&&!row.break_end)));const workedMinutes=worked?(row.break_start&&row.break_end?minutes(row.clock_in,row.break_start)+minutes(row.break_end,row.clock_out):minutes(row.clock_in,row.clock_out)):0;return{key:row.public_id,date:row.work_date,employee:row.employees,site:row.work_sites,times:{clock_in:iso(row.work_date,row.clock_in),break_start:iso(row.work_date,row.break_start),break_end:iso(row.work_date,row.break_end),clock_out:iso(row.work_date,row.clock_out)},workedMinutes,breakMinutes:minutes(row.break_start,row.break_end),complete,rejectedAttempts:0,adjustedEvents:[],occurrence:row.occurrence,batchStatus:row.manual_sheet_batches?.status};});return jsonNoStore({month,days,truncated:(result.data||[]).length===5000,source:"manual_sheet"});}
